# https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/

name: "Compile"
description: "Compile"

inputs:
  input_rmd_path:
    description: "Filename input path RmD"
    required: true
  input_rmd_file:
    description: "Filename input file Rmd"
    required: true

# https://github.com/r-lib/actions/tree/v2/examples#render-rmarkdown

runs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Install packages
        run: |
          install.packages(c("mosaic"))
        shell: Rscript {0}
              
      - name: Render Rmarkdown files and Commit Results
        run: |
          Rscript -e 'rmarkdown::render(paste0(${{inputs.input_rmd_path}}, ${{inputs.input_rmd_file}}, '.Rmd'))'

      - name: Create output dir
        run: |
          mkdir -p output
        
      - name: Copy file
        uses: canastro/copy-action@0.0.2
        with:
          source: "${{inputs.input_rmd_path}}/${{inputs.input_rmd_file}}.html"
          target: "output/${{inputs.input_rmd_file}}.html"

